name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      pull-requests: write
      issues: write
      contents: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Run Labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # ratchet:actions/labeler@v5
